/* Season 7 — 7th grade. Grown-up vocabulary, a narrator with attitude, a flashback panel. ~600 words. */
(function () {
  const S = (window.STORIES = window.STORIES || []);

  S.push({
    id: "s7e1", season: 7, num: 1, title: "Machine Day",
    blurb: "A self-driving lemonade cart, a hubcap Bolt 'found,' and the day Dr. Dullsworth ran out of time to hate.",
    cover: { bg: "street", cast: [{ who: "max", mood: "worried", pose: "run", x: 25 }, { who: "bolt", mood: "excited", pose: "run", x: 50 }, { who: "dull", mood: "surprised", x: 85, flip: true }], props: [{ e: "🛒", x: 68, y: 84, s: 60 }, { e: "🍋", x: 68, y: 66, s: 30 }], fx: "sparkle" },
    vocab: { shimmered: "Shone with a wavering, flickering light.", ambitious: "Aiming very high; hard to achieve.", spectacle: "A big, showy display that grabs attention.", inevitably: "In a way that could not be avoided.", reluctant: "Unwilling; doing something only because you have to.", dignity: "Calm, serious self-respect." },
    pages: [
      { art: { bg: "street", cast: [{ who: "zoe", mood: "happy", pose: "up", x: 25 }, { who: "mom", mood: "happy", x: 82, flip: true }], props: [{ e: "🎪", x: 55, y: 30, s: 60 }, { e: "🍦", x: 92, y: 40, s: 36 }] },
        lines: [{ n: "The first annual Machine Day arrived on a Saturday so hot the pavement shimmered, and the whole street turned out for it. Folding tables lined the sidewalk. The ice-cream truck parked at the corner and simply gave up trying to leave. Somebody had hung a banner between two lampposts that read MACHINE DAY in letters that were clearly, unmistakably, Zoe's handwriting." }] },
      { art: { bg: "garage", cast: [{ who: "max", mood: "sleepy", pose: "hold", x: 35 }], props: [{ e: "🛒", x: 70, y: 80, s: 70 }, { e: "🍋", x: 70, y: 60, s: 30 }, { e: "☕", x: 12, y: 74, s: 30 }] },
        lines: [{ n: "Max had been building for eleven days straight, which Mom allowed only because it kept {him} out of the kitchen. {His} entry was ambitious even by {his} standards: a self-driving lemonade cart that could roll up to a customer, recognize a thirsty face, and pour a cup without spilling. It had worked four times in a row. That, Max knew from painful experience, was exactly when things went wrong." }] },
      { art: { bg: "garage", cast: [{ who: "bolt", mood: "love", pose: "hold", x: 35 }, { who: "max", mood: "think", pose: "hips", x: 75, flip: true }], props: [{ e: "🛞", x: 35, y: 58, s: 40 }, { e: "✨", x: 22, y: 42, s: 26 }, { e: "✨", x: 50, y: 40, s: 26 }] },
        lines: [{ n: "Bolt had insisted on decorating. The cart was now covered in bottle caps, foil, and a hubcap he had 'found,' so that it caught the sun like a disco ball on wheels." }, { w: "bolt", t: "Customers want spectacle." }, { w: "max", t: "Customers want lemonade." }, { w: "bolt", t: "And spectacle." }, { n: "It was, annoyingly, a good point." }] },
      { art: { bg: "street", cast: [{ who: "max", mood: "think", pose: "think", x: 40 }], props: [{ e: "🛒", x: 72, y: 82, s: 60 }, { e: "💵", x: 15, y: 50, s: 40 }] },
        math: { intro: "Max counted what was left in the tank.", q: "Lemonade costs $1.25 a cup. The cart holds enough for 40 cups, but Bolt spilled 1/5 of it while polishing. How much money can Max make from the cups that are left?", answer: "$40", choices: ["$40", "$50", "$32", "$8"], hint: "1/5 of 40 cups is 8 cups spilled, so 32 cups are left. 32 × $1.25 = 32 + 8.", success: "Forty dollars, if nothing else went wrong. Bolt polished the hubcap harder." } },
      { art: { bg: "street", cast: [{ who: "max", mood: "happy", pose: "point", x: 25 }, { who: "zoe", mood: "happy", pose: "cheer", x: 55, scale: .9 }, { who: "dull", mood: "think", pose: "hips", x: 88, flip: true }], props: [{ e: "🛒", x: 40, y: 84, s: 50 }, { e: "🌋", x: 62, y: 80, s: 40 }, { e: "🧻", x: 88, y: 84, s: 34 }], fx: "sparkle" },
        lines: [{ n: "By noon, the cart had served thirty people, rolled over one foot, and been hugged by a toddler who would not let go. Zoe's entry, a baking-soda volcano that erupted on a timer, drew a bigger crowd, but Max was too busy to be jealous. Dr. Dullsworth's entry, a machine that folded napkins into perfect squares, drew nobody. He sat behind it with his arms crossed, watching Max's cart with an expression that was difficult to read." }] },
      { art: { bg: "night", cast: [{ who: "bolt", mood: "think", pose: "hold", x: 50 }], props: [{ e: "🍞", x: 20, y: 40, s: 44 }, { e: "➡️", x: 35, y: 40, s: 30 }, { e: "💭", x: 72, y: 32, s: 60 }], fx: "dark" },
        lines: [{ n: "Here is what Bolt was thinking, since nobody asked. He was thinking that a year ago he had been a toaster. A good toaster, sure, but a toaster: something you push down and wait for. Now he had a tail, a name, a sister who yelled his name, and a best friend who pointed shrink rays at him by accident. He had flown ten feet. He had been banned from a gym. If someone had told the toaster all of this, the toaster would not have believed it. Bolt found this hilarious. He also found it, though he would deny it under any questioning, a little bit moving." }] },
      { art: { bg: "street", cast: [{ who: "max", mood: "worried", pose: "run", x: 20 }, { who: "bolt", mood: "surprised", pose: "run", x: 42 }, { who: "dull", mood: "surprised", pose: "up", x: 88, flip: true }], props: [{ e: "🛒", x: 66, y: 84, s: 60 }, { e: "🍋", x: 66, y: 60, s: 26 }, { e: "💦", x: 76, y: 70, s: 34 }], fx: "boom" },
        lines: [{ n: "At 2:15, inevitably, the cart went rogue. Its face-recognizer locked onto the hubcap's own reflection, decided the hubcap was thirsty, and began pouring lemonade onto itself in a slow, dignified circle. Max lunged. Bolt lunged. The cart, sensing spectacle, sped up. It rolled through Zoe's crowd, sprayed the volcano until it fizzed early, and finally came to rest against Dr. Dullsworth's napkin machine, which it drenched completely." }] },
      { art: { bg: "street", cast: [{ who: "dull", mood: "think", pose: "hold", x: 65, flip: true }, { who: "max", mood: "worried", x: 25 }], props: [{ e: "🧻", x: 65, y: 60, s: 30 }, { e: "🛒", x: 45, y: 86, s: 50 }] },
        lines: [{ n: "There was a silence. Dr. Dullsworth stood. He looked at his ruined napkins, at the sticky cart, at Max, who had gone the pale color of someone about to apologize for the rest of his life. Then the old man picked up a soggy napkin, folded it once, perfectly, and set it on the cart like a tiny flag." }, { w: "dull", t: "Reckless. Loud. Unlicensed." }, { n: "He paused." }, { w: "dull", t: "Do you have any lemonade left?" }] },
      { art: { bg: "street", cast: [{ who: "cat", mood: "sly", x: 15, y: 90 }, { who: "dull", mood: "happy", pose: "hold", x: 40 }, { who: "max", mood: "happy", pose: "hold", x: 68 }, { who: "bolt", mood: "excited", x: 90, flip: true, scale: .9 }], props: [{ e: "🏆", x: 15, y: 62, s: 34 }, { e: "🥈", x: 40, y: 58, s: 30 }, { e: "🎗️", x: 68, y: 58, s: 30 }, { e: "🎧", x: 88, y: 18, s: 24 }] },
        lines: [{ n: "The trophy went to the cat, again, for a project nobody could locate. Second place went to Dr. Dullsworth, who accepted it with the reluctant dignity of a man who had planned to hate the whole day and had simply run out of time. Max got a ribbon that said PARTICIPANT, which Bolt immediately covered in foil so it would shine." }, { w: "max", t: "Next year." }, { w: "bolt", t: "Next year, we add a jetpack." }, { n: "Somewhere on a rooftop, a small gray headset clicked on, and a cat made a note." }] },
    ],
    quiz: [
      { q: "What was Max's Machine Day entry?", c: ["A napkin folder", "A volcano on a timer", "A self-driving lemonade cart", "A jetpack"], a: 2 },
      { q: "Why did the cart start pouring lemonade on itself?", c: ["Bolt pushed the wrong button", "It saw its own reflection in the hubcap and thought it was a thirsty face", "It ran out of cups", "Zoe hacked it"], a: 1 },
      { q: "What does 'reluctant dignity' tell you about Dr. Dullsworth at the end?", c: ["He was furious", "He wanted to leave", "He enjoyed the day but did not want to admit it", "He did not understand the prize"], a: 2 },
    ],
  });
})();
